version: 2

updates:
  - package-ecosystem: npm
    directory: /frontend
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5

  - package-ecosystem: maven
    directory: /backend
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /backend
    target-branch: develop
    schedule:
      interval: weekly
      day: tuesday
      time: "06:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 2

  - package-ecosystem: docker
    directory: /frontend
    target-branch: develop
    schedule:
      interval: weekly
      day: tuesday
      time: "06:30"
      timezone: Europe/Berlin
    open-pull-requests-limit: 2

  - package-ecosystem: docker-compose
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: tuesday
      time: "07:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 2

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: wednesday
      time: "06:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 3
