services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - backend-maven-cache:/root/.m2

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules

volumes:
  backend-maven-cache:
  frontend-node-modules:
