spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/todo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:todo}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:todo}
